### PR TITLE
fix send email error

### PR DESCRIPTION
**Pull request by wang14597**
Hi @alexisrolland:
This is my first time to submitted a pull request on an open source project.
If there are any deficiencies, please give me more advice.

#364 fix send email error when use other email server

### CODE REVIEW

**Comment by alexisrolland** [comment]
Thank you for your pull request!
Could you please confirm this was tested and worked with QQ mail?

The previous code was working for Gmail so I would suggest to not change it. Instead I would propose the following:

- Move the line `connection = smtplib.SMTP(...)` in the code block `If config['host'] == "smtp.gmail.com":`

- Add a new code block `If config['host'] == "smtp.qq.com":` and place `connection = smtplib.SMTP_SSL(...)` in it

- Add an `else:` code block to manage other fallback cases.

Thanks again!

**Comment by wang14597** [comment]
#### Thank you very much for your suggestions.
#### I thought `smtplib.SMTP_SSL(...)` would not report an error when using gmail,but I was wrong.
#### I just did a test and found that `smtplib.SMTP_SSL(...)` cannot support the sending of gmail, it's my mistake.
#### And I confirmed that `smtplib.SMTP_SSL(...)` can support qq email.
#### I will modify code.
#### Thank you very much!

**Comment by wang14597** [comment]
#### I was thinking, may i use try catch? like this：
```
try:
    connection = smtplib.SMTP_SSL(config['host'], config['port'])
except Exception:
    connection = smtplib.SMTP(config['host'], config['port'])
```
#### In this way, we don’t need to consider that type of email service. It will only have two options, and only one of them will take effect

**Review by alexisrolland — APPROVED** [review]
Looks good to me! Thank you for your pull request <3

**Pull request merged**
